---
- name: Fact gather stat
  hosts: webservers
  remote_user: root
  become: yes
  tasks:
   - name: install httpd
     yum:
      name: httpd
      state: installed
    - name: cp index.html
      copy:
        src: index.html
        dest: /var/www/html
    - name: service mod
      service:
        name: httpd
        state: present
        
